categories:
  - title: 'BREAKING CHANGES'
    labels:
      - 'BREAKING CHANGES'
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Fixes'
    labels:
      - 'fix'
      - 'bug'
      - 'security'
  - title: 'Dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'
      - 'renovate'
  - title: 'Documentation'
    labels:
      - 'document'
      - 'documentation'
  - title: 'Internal improvement'
    labels:
      - 'ci'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'BREAKING CHANGES'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'fix'
      - 'security'
  default: patch

