name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
  # Comment out to enable these permissions if needed.
  # packages: write
  # deployments: write
  # id-token: write

jobs:
  draft_release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release-drafter.outputs.tag_name }}
    steps:
      # Get next version
      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        with:
          config-name: release-drafter-git-contribution-react-heatmap-cli.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Sample job for GitHub Actions repository.
  # It creates GitHub Releases and push semver(major, minor, patch) git tags.
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: draft_release
    steps:
      - name: Create semver outputs
        uses: actions/github-script@v6
        id: semver
        with:
          script: |
            const TAG_NAME = "${{ needs.release-drafter.outputs.tag_name }}"
            const matched = TAG_NAME.match(/(((git-contribution-react-heatmap-cli@\d+)\.\d+).\d+)/)
            core.setOutput('major', matched[3])
            core.setOutput('minor', matched[2])
            core.setOutput('patch', matched[1])
            
      - uses: actions/checkout@v4
        with:
          ref: "${{ needs.release-drafter.outputs.tag_name }}"

      # Build packages with bun
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          registry-url: 'https://registry.npmjs.org'
      - run: bun build-packages

      # Publish packages to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '21.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
            npm version ${{ needs.semver.outputs.major }}.${{ needs.semver.outputs.minor }}.${{ needs.semver.outputs.patch }}
            npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update major and minor git tags
        run: |
           git push -f origin "refs/tags/${{ needs.release-drafter.outputs.tag_name }}:refs/tags/${{ needs.semver.outputs.major }}"
           git push -f origin "refs/tags/${{ needs.release-drafter.outputs.tag_name }}:refs/tags/${{ needs.semver.outputs.minor }}"

      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        with:
          config-name: release-drafter-git-contribution-react-heatmap-cli.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}