name: Release Storybook to GitHubPages

on:
  push:
    branches:
      - main

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
  release:
    name: Publish Storybook
    runs-on: ubuntu-latest
    env:
        TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
            bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Cache bun dependencies
        uses: actions/cache@v3
        id: bun-cache
        with:
            path: node_modules
            key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
            restore-keys: ${{ runner.os }}-bun

      - name: Install dependencies if cache invalid
        if: steps.bun-cache.outputs.cache-hit != 'true'
        run: bun i --frozen-lockfile

      #👇 Add Storybook build and deploy to GitHub Pages as a step in the workflow
      - name: Publish Storybook
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.1
        with:
          build_command: bun run build:storybook
          path: ./packages/ui/storybook-static
          checkout: false # def