name: Release Storybook to GitHubPages

on: [push]

jobs:
  release:
    name: Project Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
            bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Cache bun dependencies
        uses: actions/cache@v3
        id: bun-cache
        with:
            path: node_modules
            key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
            restore-keys: ${{ runner.os }}-bun

      - name: Install dependencies if cache invalid
        if: steps.bun-cache.outputs.cache-hit != 'true'
        run: bun i --frozen-lockfile

      - name: Build storybook of @repo/ui
        run: bun run build:storybook

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/ui/storybook-static