# https://zenn.dev/aiji42/articles/6656072a954a9b 
name: Visual Regression Testing Update By PR Comment

on:
  issue_comment:
    types: [created, edited]

jobs:

  lost-pixel:
    # PR中のコメントに /update-vrt と入力するとアクションが発動する
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/update-vrt')
    name: 📸 Lost Pixel Baseline Update By PR Comment
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    permissions:
      contents: write
      pull-requests: write

    strategy:
      matrix:
        config:
          - { package: "apps/blog", name: "Lost Pixel for blog page", command: "bun run start" }

    defaults:
      run:
        working-directory: ${{ matrix.config.package }}

    steps:
      - name: Get branch name
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Commit
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          fetch-depth: 0 # 全ブランチの履歴を取得

      - name: Setup Bun  
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: cd ../../ && bun install

      - name: Build UI
        working-directory: ./packages/ui
        run: bun run build 

      - name: Build App
        run: cd ../../ && bun run build 

      - name: Start App
        run: cd . && ${{ matrix.config.command }} &

      - name: Lost Pixel Update
        id: lostpixel
        uses: lost-pixel/lost-pixel@v3.16.0
        env:
          LOST_PIXEL_MODE: update
          LOST_PIXEL_DISABLE_TELEMETRY: 1
          LOST_PIXEL_CONFIG_DIR: ${{ matrix.config.package }}
      
      - name: Lost Pixel
        if: ${{ failure() && steps.lostpixel.conclusion == 'failure' }}
        uses: lost-pixel/lost-pixel@v3.16.0
        env:
          LOST_PIXEL_DISABLE_TELEMETRY: 1
          LOST_PIXEL_CONFIG_DIR: ${{ matrix.config.package }}

      - name: Give Permission to untracked files
        if: ${{ failure() && steps.lostpixel.conclusion == 'failure' }}
        run: sudo chown -R $USER:$USER .

      - name: Create new branch
        if: ${{ failure() && steps.lostpixel.conclusion == 'failure' }}
        run: |
          git checkout -b lost-pixel-update/${{ steps.comment-branch.outputs.head_ref  }}
      
      - name: Add untracked files
        if: ${{ failure() && steps.lostpixel.conclusion == 'failure' }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add .
      
      - name: Create commit
        if: ${{ failure() && steps.lostpixel.conclusion == 'failure' }}
        run: |
          git commit -m "Update VRT baseline images"
      
      - name: Create Pull Request
        if: ${{ failure() && steps.lostpixel.conclusion == 'failure' }}
        run: |
          gh pr create --base ${{ steps.comment-branch.outputs.head_ref  }} \
                       --head lost-pixel-update/${{ steps.comment-branch.outputs.head_ref  }} \
                       --label update-lost-pixel \
                       --title 'Lost Pixel Update - ${{ steps.comment-branch.outputs.head_ref  }}' \
                       --body 'Automated baseline update created by Lost Pixel'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
