# https://zenn.dev/aiji42/articles/6656072a954a9b 
name: Visual Regression Testing Update By PR Comment

on:
  issue_comment:
    types: [created, edited]

jobs:

  lost-pixel:
    # PR中のコメントに /update-vrt と入力するとアクションが発動する
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/update-vrt')
    name: 📸 Lost Pixel Baseline Update By PR Comment
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    permissions:
      contents: write
      pull-requests: write

    strategy:
      matrix:
        config:
          - { package: "apps/blog", name: "Lost Pixel for blog page", command: "bun run start" }

    defaults:
      run:
        working-directory: ${{ matrix.config.package }}

    steps:

      - name: Checkout Commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 全ブランチの履歴を取得

      - name: Setup Bun  
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: cd ../../ && bun install

      - name: Build UI
        working-directory: ./packages/ui
        run: bun run build 

      - name: Build App
        run: cd ../../ && bun run build 

      - name: Start App
        run: cd . && ${{ matrix.config.command }} &

      - name: Lost Pixel Update
        id: lostpixel
        uses: lost-pixel/lost-pixel@v3.16.0
        env:
          LOST_PIXEL_MODE: update
          LOST_PIXEL_DISABLE_TELEMETRY: 1
          LOST_PIXEL_CONFIG_DIR: ${{ matrix.config.package }}
      
      - name: Lost Pixel
        if: ${{ failure() && steps.lostpixel.conclusion == 'failure' }}
        uses: lost-pixel/lost-pixel@v3.16.0
        env:
          LOST_PIXEL_DISABLE_TELEMETRY: 1
          LOST_PIXEL_CONFIG_DIR: ${{ matrix.config.package }}

      - name: Give Permission to untracked files
        if: ${{ failure() && steps.lostpixel.conclusion == 'failure' }}
        run: sudo chown -R $USER:$USER .

      - name: Create Pull Request
        if: ${{ failure() && steps.lostpixel.conclusion == 'failure' }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          commit-message: Update VRT baseline images
          branch: lost-pixel-update/${{ github.ref_name }}
          title: 'Lost Pixel update - ${{ github.ref_name }}'
          body: Automated baseline update PR created by Lost Pixel