on: workflow_dispatch

jobs:
  lost-pixel-update:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          config:
            - {
                package: "apps/blog",
                name: "Lost Pixel for blog page",
                command: "bun run start",
              }
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    permissions:
        contents: write
        pull-requests: read
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
         fetch-depth: 2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
         bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Cache bun dependencies
        uses: actions/cache@v3
        id: bun-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun

      - name: Build
        run: bun run build

      - name: Start App
        run: cd ${{ matrix.config.package }} && ${{ matrix.config.command }} & 
    
      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v3.16.0
        env:
          LOST_PIXEL_MODE: update
          LOST_PIXEL_DISABLE_TELEMETRY: 1
          LOST_PIXEL_CONFIG_DIR: ${{ matrix.config.package }}

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ failure() && steps.lostpixel.conclusion == 'failure' }}
        with:
          commit_message: update lost-pixel baselines