on: [push]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          config:
            - {
                package: "apps/blog",
                name: "Lost Pixel for blog page",
                command: "bun run start",
              }
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Cache bun dependencies
        uses: actions/cache@v3
        id: bun-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun

  vrt:
    needs: install-dependencies
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./apps/blog
    strategy:
        matrix:
          config:
            - {
                package: "apps/blog",
                name: "Lost Pixel for blog page",
                command: "bun run start",
              }

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Restore bun dependencies
        id: bun-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun
     
      - name: Build
        run: cd ../../ && bun run build

      - name: Start App
        run: ${{ matrix.config.command }}
      
      - name: Check where I am
        run: pwd
        
        
      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v3.8.0
        env:
            LOST_PIXEL_CONFIG_DIR: ${{ matrix.config.package }}
